version: "1.0"
name: "棋牌游戏平台开发工作流"

stages:
  - name: "需求分析"
    agent: "product-manager"
    tasks:
      - "分析用户需求"
      - "编写PRD文档"
      - "竞品分析"
      - "功能优先级排序"
    output:
      - "PRD.md"
      - "功能列表.md"

  - name: "设计阶段"
    agent: "ui-ux-designer"
    depends_on: ["需求分析"]
    tasks:
      - "界面设计"
      - "交互原型"
      - "设计规范"
    output:
      - "设计稿.fig"
      - "设计规范.md"

  - name: "开发阶段"
    parallel: true
    agents:
      - name: "frontend-engineer"
        tasks:
          - "前端项目初始化"
          - "组件开发"
          - "页面开发"
          - "状态管理"
          - "WebSocket集成"
      - name: "backend-engineer"
        tasks:
          - "后端项目初始化"
          - "API开发"
          - "数据库设计"
          - "用户系统"
      - name: "game-logic"
        tasks:
          - "游戏算法实现"
          - "房间管理"
          - "计分系统"
          - "匹配系统"
    depends_on: ["设计阶段"]

  - name: "测试阶段"
    agent: "qa-engineer"
    depends_on: ["开发阶段"]
    tasks:
      - "编写测试用例"
      - "单元测试"
      - "集成测试"
      - "E2E测试"
      - "性能测试"
    output:
      - "测试报告.md"

  - name: "部署阶段"
    agent: "devops-security"
    depends_on: ["测试阶段"]
    tasks:
      - "Docker镜像构建"
      - "CI/CD配置"
      - "K8s部署"
      - "监控配置"

  - name: "质量验收"
    agent: "commander"
    depends_on: ["部署阶段"]
    tasks:
      - "代码审查"
      - "安全扫描"
      - "性能验收"
      - "体验评分 (连续3次≥9.5分)"
    output:
      - "验收报告.md"
    gate:
      min_score: 9.5
      required_consecutive: 3

flow_control:
  on_failure:
    - "记录问题"
    - "分析原因"
    - "调度对应Agent重做"
  on_success:
    - "生成交付文档"
    - "通知团队"
